name = "jlPackageSfpn"
uuid = "3cb67a9e-6634-4746-b05e-e3bee56fd255"
authors = ["ranto <rantohary@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
